### ISSUE TITLE
Content with leading and trailing whitespace trimmed

### ISSUE THREAD

**Issue by mainrs** [the-alchemists-of-arland/gray-matter-rs#14]
```hbs
---
key: "Value"
---
    This is my content
```
gets parsed to 

```rust
ParsedEntity {
    content: "This is my content"
}
``` 

Maybe introducing a configuration field for `Matter` to allow to set whether whitespace gets trimmed or not. Can be true by default for backwards compatibility.

 A simple change to this line is not sufficient enough as the content then contains a leading newline: https://github.com/the-alchemists-of-arland/gray-matter-rs/blob/4abb676f76f86f05a644e3102cc6c61e466fab28/src/matter.rs#L122
 
 ```
 \n    This is my content
 ```

**Comment by mainrs** [comment]
Would yo mind pushing a new version (0.2.2) @yuchanns?

**Comment by yuchanns** [comment]
> Would yo mind pushing a new version (0.2.2) @yuchanns?

Done
