### ISSUE TITLE
Outdated Rust version in Workflows

### ISSUE THREAD

**Issue by kmaasrud** [the-alchemists-of-arland/gray-matter-rs#8]
You seem to be using Rust 1.49 in both the `main.yml` and the `publish.yml` workflow. See:

https://github.com/the-alchemists-of-arland/gray-matter-rs/blob/a95f707601e427a817d9757a7b618c83328700a7/.github/workflows/main.yml#L16

It seems I don't have direct push access to the `main` branch (needs review), so I can't change this. @yuchanns, could you update the workflow to the latest Rust version? The latest stable is [1.55](https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html), and my pending PR needs at least [1.52](https://blog.rust-lang.org/2021/05/06/Rust-1.52.0.html)

**Comment by yuchanns** [comment]
It has been fixed now
